<h1 class="mt-5">Add task</h1>

<div class="row mt-3">
    <div class="col">
        <a href="<?php echo $this->url->get(['for' => 'home']); ?>" class="btn btn-primary">Return to list</a>
    </div>
</div>

<div class="row mt-3">
    <div class="col">

        <form action="" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label>Name *</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fa fa-user"></i>
                            </span>
                        </div>
                        <input type="text" class="form-control" name="user_name" placeholder="" value="" required="">
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label>Email *</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fa fa-envelope-open"></i>
                            </span>
                        </div>
                        <input type="text" class="form-control" name="email" placeholder="" required="">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <label>Image *</label>
                    <input type="file" class="form-control" name="image" required="" accept=".jpg, .jpeg, .png, .gif">
                </div>
            </div>

            <hr class="mb-4">

            <div class="row">
                <div class="col">
                    <label>Message *</label>
                    <textarea name="message" class="form-control" required=""></textarea>
                </div>
            </div>

            <?php if ($this->formErrorMessage) : ?>
                <div class="alert alert-danger">
                    <?php echo $this->formErrorMessage; ?>
                </div>
            <?php endif; ?>

            <hr class="mb-4">
            <button class="btn btn-primary" type="submit">Add</button>
        </form>

    </div>
</div>
