<h1 class="mt-5">Delete task</h1>

<div class="row mt-3">
    <div class="col">
        <a href="<?php echo $this->url->get(['for' => 'home']); ?>" class="btn btn-primary">Return to list</a>
    </div>
</div>

<hr class="mb-4">

<div class="row mt-3">
    <div class="col">
        <p>ID: <?php echo $this->taskModel->id; ?></p>
        <p>User: <?php echo $this->taskModel->user_name; ?></p>
        <p>Email: <?php echo $this->taskModel->email; ?></p>
        <p>Date: <?php echo $this->taskModel->getCreatedAt()->format('d.m.Y \i\n H:i'); ?></p>
        <p>Status:
            <?php if ($this->taskModel->status) : ?>
                <span class="task-status-1"><i class="fa fa-check"></i></span>
            <?php else : ?>
                <span class="task-status-0"><i class="fa fa-times"></i></span>
            <?php endif; ?>
        </p>
        <p><?php echo $this->taskModel->message; ?></p>
    </div>
</div>

<hr class="mb-4">

<div class="row mt-3">
    <div class="col">
        Delete this task?
        <a href="?delete=y" class="btn btn-primary">Delete</a>
    </div>
</div>