<h1 class="mt-5">Task card</h1>

<div class="row mt-3">
    <div class="col">
        <a href="<?php echo $this->url->get(['for' => 'home']); ?>" class="btn btn-primary">Return to list</a>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        <?php if ($this->security->getUser()) : ?>
            <td>
                <a href="<?php echo $this->url->get(['for' => 'task-edit', 'id' => $this->taskModel->id]); ?>" class="btn btn-success btn-sm">
                    <i class="fa fa-pencil-alt"></i>
                </a>
                <a href="<?php echo $this->url->get(['for' => 'task-delete', 'id' => $this->taskModel->id]); ?>" class="btn btn-danger btn-sm">
                    <i class="fa fa-times"></i>
                </a>
            </td>
        <?php endif; ?>
    </div>
</div>

<hr class="mb-4">

<div class="row mt-3">
    <div class="col">
        <p>ID: <?php echo $this->taskModel->id; ?></p>
        <p>User: <?php echo $this->taskModel->user_name; ?></p>
        <p>Email: <?php echo $this->taskModel->email; ?></p>
        <p>Date: <?php echo $this->taskModel->getCreatedAt()->format('d.m.Y \i\n H:i'); ?></p>
        <p>Status:
            <?php if ($this->taskModel->status) : ?>
                <span class="task-status-1"><i class="fa fa-check"></i></span>
            <?php else : ?>
                <span class="task-status-0"><i class="fa fa-times"></i></span>
            <?php endif; ?>
        </p>
        <p><?php echo $this->taskModel->message; ?></p>
        <?php if (!empty($this->taskModel->getImagePath())) : ?>
            <img src="<?php echo $this->taskModel->getImagePath(); ?>" alt="">
        <?php endif; ?>
    </div>
</div>
