<div class="text-center">
    <form class="form-signin" method="post" action="<?php echo $this->url->get(['for' => 'security-login']); ?>">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <input type="text" name="login" class="form-control" placeholder="Login" required autofocus>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <?php if ($this->formErrorMessage) : ?>
            <div class="alert alert-danger">
                <?php echo $this->formErrorMessage; ?>
            </div>
        <?php endif; ?>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>