<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo $this->title; ?></title>
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/css/fontawesome-all.min.css" rel="stylesheet">
    <link href="/assets/css/style.css" rel="stylesheet">
</head>
<body>
<?php echo $this->partial('partials/header'); ?>
<main role="main" class="container">
    <?php echo $this->getContent(); ?>
</main>
<?php echo $this->partial('partials/footer'); ?>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
</body>
</html>